# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GamebaseSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GamebaseSampleApp
  # Rx
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  # Library
  pod 'SideMenu', '6.5.0'
  pod 'SnapKit', '5.6.0'
  pod 'MBProgressHUD', '1.2.0'
  pod 'QuickTableViewController', '1.3.1'

  # Gamebase
  pod 'Gamebase', '2.43.3'
  pod 'GamebaseAuthFacebookAdapter', '2.43.3'
  pod 'GamebaseAuthGamecenterAdapter', '2.43.3'
  pod 'GamebaseAuthPaycoAdapter', '2.43.3'
  pod 'GamebaseAuthNaverAdapter', '2.43.3'
  pod 'GamebaseAuthTwitterAdapter', '2.43.3'
  pod 'GamebaseAuthGoogleAdapter', '2.43.3'
  pod 'GamebaseAuthLineAdapter', '2.43.3'
  pod 'GamebaseAuthAppleidAdapter', '2.43.3'
  pod 'GamebaseAuthWeiboAdapter', '2.43.3'
  pod 'GamebasePushAdapter', '2.43.3'
  pod 'GamebasePurchaseIAPAdapter', '2.43.3'
  
  # 아래 모듈의 사용 방법은 고객센터로 문의하시기 바랍니다.
  # pod 'GamebaseAuthHangameAdapter', '2.43.3'
  pod 'GamebaseAuthKakaogameAdapter', '2.43.3'

  target 'GamebaseSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GamebaseSampleAppUITests' do
    # Pods for testing
  end

end
