# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GamebaseSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GamebaseSampleApp
  # Rx
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  # Library
  pod 'SideMenu', '6.5.0'
  pod 'SnapKit', '5.6.0'
  pod 'MBProgressHUD', '1.2.0'
  pod 'QuickTableViewController', '1.3.1'

  # Gamebase
  $GAMEBASE_SDK_VERSION = '2.55.0'
  pod 'Gamebase', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthFacebookAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthGamecenterAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthPaycoAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthNaverAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthTwitterAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthGoogleAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthLineAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthAppleidAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthWeiboAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebasePushAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebasePurchaseIAPAdapter', $GAMEBASE_SDK_VERSION
  
  # 아래 모듈의 사용 방법은 고객센터로 문의하시기 바랍니다.
  # pod 'GamebaseAuthHangameAdapter', $GAMEBASE_SDK_VERSION
  pod 'GamebaseAuthKakaogameAdapter', $GAMEBASE_SDK_VERSION

  target 'GamebaseSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GamebaseSampleAppUITests' do
    # Pods for testing
  end

end

# 참고: https://stackoverflow.com/questions/72561696/xcode-14-needs-selected-development-team-for-pod-bundles
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
  
end
